services:
  mijn-database:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: super_geheim
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - db-data:/var/lib/mysql

  mijn-website:
    image: wordpress:latest
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: mijn-database
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wordpress_db
    depends_on:
      - mijn-database
    volumes:
      - wp-data:/var/www/html

volumes:
  db-data:
  wp-data: